#!/bin/bash

# If not, Set timezone
if [ ! -e "/etc/timezone" ] && [ -z "${TZ}" ]; then
    export TZ="America/Chicago"
fi

# Set LANG for perl
if [ -z "${LANG}" ]; then
    export LANG=C
fi

# Allow running a bash session, otherwise pass everything to sqitch
if [[ "$1" == *"bash" ]]; then
    /bin/env bash
else
    sqitch "$@"
fi
